opendatakit/skunkworks-crow

share_app/src/main/AndroidManifest.xml, share_app/src/main/java/org/odk/share/activities/MainActivity.java, share_app/src/main/java/org/odk/share/controller/WifiHotspotHelper.java, share_app/src/main/java/org/odk/share/services/HotspotService.java, share_app/src/main/res/values/strings.xml
Closes #19 
Devices with android version >= 7 is able to create and enable hotspot network from the app but no other devices are able to connect to it.
To fix this issue, a check is added so that user can navigate to hotspot settings and then have to enable from their, then only other devices will be able to connect to it.
=> Enable hotspot from settings

share_app/src/main/AndroidManifest.xml, share_app/src/main/java/org/odk/share/activities/SendActivity.java, share_app/src/main/java/org/odk/share/activities/WifiActivity.java, share_app/src/main/res/values/strings.xml
Fixes #33 
[WifiManager](https://developer.android.com/reference/android/net/wifi/WifiManager#startLocalOnlyHotspot(android.net.wifi.WifiManager.LocalOnlyHotspotCallback,%20android.os.Handler))
For devices having android version >= 8 they have added public API which can be used to enable and disable the hotspot. 3rd party apps can only enable/disable it, they are not allowed to change the WifiConfiguration. 
For Oreo or greater versions, user have to scan the QR Code to connect to the network.
Useful Links- 
[https://stackoverflow.com/questions/45984345/how-to-turn-on-off-wifi-hotspot-programmatically-in-android-8-0-oreo/45996578#45996578](https://stackoverflow.com/questions/47700717/change-wifi-hotspots-ssid-and-password-in-android-oreo-8-x) …
=> Hotspot connection issue resolved for devices >= Oreo

share_app/src/main/AndroidManifest.xml, share_app/src/main/java/org/odk/share/activities/SendActivity.java, share_app/src/main/res/values/strings.xml
Closes #72 
Screen orientation issue resolved and added a dialog before turning the hotspot off so that user can know that leaving the activity may stop the connection.
For future, we can have an option to run the hotspot connection throughout the activities.
=> Dialog added before hotspot is stopped

share_app/src/main/AndroidManifest.xml, share_app/src/main/java/org/odk/share/activities/InstancesList.java, share_app/src/main/java/org/odk/share/activities/MainActivity.java, share_app/src/main/java/org/odk/share/activities/ReviewFormActivity.java, share_app/src/main/java/org/odk/share/activities/SendActivity.java, share_app/src/main/java/org/odk/share/activities/WifiActivity.java, share_app/src/main/java/org/odk/share/adapters/TransferInstanceAdapter.java, share_app/src/main/java/org/odk/share/application/Share.java, share_app/src/main/java/org/odk/share/dao/InstanceMapDao.java, share_app/src/main/java/org/odk/share/dao/TransferDao.java, share_app/src/main/java/org/odk/share/database/ShareDatabaseHelper.java, share_app/src/main/java/org/odk/share/dto/InstanceMap.java, share_app/src/main/java/org/odk/share/dto/TransferInstance.java, share_app/src/main/java/org/odk/share/fragments/ReviewedInstancesFragment.java, share_app/src/main/java/org/odk/share/fragments/SentInstancesFragment.java, share_app/src/main/java/org/odk/share/provider/InstanceMapProvider.java, share_app/src/main/java/org/odk/share/services/SenderService.java, share_app/src/main/java/org/odk/share/tasks/DownloadJob.java, share_app/src/main/java/org/odk/share/tasks/UploadJob.java, share_app/src/main/java/org/odk/share/utilities/ApplicationConstants.java, share_app/src/main/res/values/strings.xml
Closes #81 
- Feedback is only sent to the enumerator who asked for the review.
- Sent tabs updated (Now the buttons are removed only it shows information about the sent forms and the feedback/reviewStatus received by the receiver)
- Transfer result dialog contains result about individual blank form, filled form status.
- Sending same form again and again will not create seperate entries for every transfer, it will update the same existing form with the new files received.
=> Added UUID to forms so that forms can be identified uniquely

skunkworks_crow/build.gradle
Closes #159 
updated to RXjava 2.2.7
tested in the android studio and no new warnings are given and I also transferred files using my phone no issues I get
according to new releases [RXjava](https://github.com/ReactiveX/RxJava/releases) from 2.0.2 to 2.2.7 
I updated the dependencies and Rxandroid also
This specification itself has evolved out of RxJava 1.x and provides a common baseline for reactive systems and new libraries.
it follows the Reactive-Streams architecture and New primitive types aslo
=> Udated the RX java2 dependencies

skunkworks_crow/src/main/java/org/odk/share/fragments/SentInstancesFragment.java
Closes #184 
I made the app run on a device and it's showing the expected result.
The two buttons "Send" and "Select All" are removed as there was no use of them.
This was the best possible solution for the result to be seen and redundancy to be eliminated
It improves the UI/UX.
=> Buttons removed in "Sent" tab

skunkworks_crow/src/main/java/org/odk/share/preferences/SettingsPreference.java
Closes #153 
Tested on my phone Samsung J8 is working fine as expected
I gave the else statement in that I made using the setsummary so then it is updating immediately
By updating the name immediately the user knows he updated the name instead of he has to come back
=> Hotspot name is changing immediately now

skunkworks_crow/src/main/res/layout/fragment_stats.xml
Closes #204 
I made it run on my Android Device and it is showing the expected result.
This is perhaps the best solution. Just a few lines of code added to the file
It improves UI/UX. Now the users would be able to view the whole "Statistics" activity.
=> Statistics fragment issue fixed

skunkworks_crow/src/main/AndroidManifest.xml, skunkworks_crow/src/main/java/org/odk/share/activities/AboutActivity.java, skunkworks_crow/src/main/java/org/odk/share/activities/InstanceManagerTabs.java, skunkworks_crow/src/main/java/org/odk/share/activities/SendFormsActivity.java, skunkworks_crow/src/main/java/org/odk/share/activities/WifiActivity.java, skunkworks_crow/src/main/java/org/odk/share/preferences/SettingsPreference.java
Closes #108 
Tested it in circumstances such as:
* Clicking on the up button.
* Pressing back
This is the best possible solution according to [Android Documentation](https://developer.android.com/training/appbar/up-action)
No risks are associated with these changes.
=> Add Up Button In Activities For Better Navigation

skunkworks_crow/src/main/java/org/odk/share/adapters/InstanceAdapter.java
Closes #111
Verified in physical device Realme U1, Android 8.1.
Unchecked direct access to cursor was causing StaleDataException. Adding cursor-close-check solves this.
=> Solves crash issue, due to missing cursor check.

skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java, skunkworks_crow/src/main/res/values/strings.xml
Closes #219 
- Checked and verified starting hot stop was blocked and only resumed once app had location permission
on one plus 3T (Oreo) and Android Emulator (Oreo).
- It sets `isHotspotInitiated` as false, if location is not turned on while trying to use hotspot. so it fits with the existing logic
- Maybe move `isGPSenabled()` to a util class
- Add runtime permissions  along with checking if GPS is enabled, but version code is set to 22 so that's probably a no for now
- User's with Oreo or higher see a dialog to turn on location, while trying to send a file.
- My changes conflict with #218
=> [#219]  checks if gps is on for >= oreo, when hotspot is turned on

skunkworks_crow/src/main/java/org/odk/share/activities/MainActivity.java
Closes #228 
I have test in my Nexus 6P new device.
I just wrapped the method `createODKDirs()` since only the first time we install the application, and without an ODK dir (without permission to storage) will face this error.
N/A
=> 🚑 quickfix: Added permission check when first enter application

skunkworks_crow/build.gradle, skunkworks_crow/src/main/res/layout/activity_review_form.xml
Closes #236 
1. Checks if the app is crashing on clicking received forms 
2. Checked any new warnings are produced
3. Whether it is directing to review form 
The app is crashing due to `android.support.design.widget.TextInputLayout` so I imported dependencies from `google android material` 
and stopped the warning of `autofill`
App crash is not at all the good behavior, so removed that behavior
by directing into review form so the user can review the forms or view it on ODK collect
=> Stops app crash on entering received forms

skunkworks_crow/src/main/java/org/odk/share/preferences/SettingsPreference.java, skunkworks_crow/src/main/res/layout/dialog_password_til.xml, skunkworks_crow/src/main/res/xml/preferences_menu.xml
Closes #216 
- Opened settings screen
- Checked if toggle worked
- Checked if changed password was saved
- Checked if default password was loaded, when setting password for the first time
- Easiest method of achieving password toggle
- However, using a checkbox to toggle was considered but was quickly ruled out after following the discussion on #221 
- User can now toggle password in input area
=> [#216] replaced edittextpref with textinputlayout dialog

skunkworks_crow/src/main/res/layout/activity_web_view.xml
Closes #245 
Checked whether App is crashing or not
checked whether web view of open source licenses are opening or not
And checked any new warnings are producing  
As by using `android.support.v7.widget.Toolbar` so the layout is inflating so I changed to  `androidx.appcompat.widget.Toolbar ` so by using the support of android RX so I fixed that
By solving the app crash on clicking so that a user can see the web view of open source licenses
=> Fixed App crash in open source licenses

skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java
Closes #275 
I just removed the `addBondedDevices()` method, since we don't need all the paired devices. 
Those changes tested well in my Nexus 6P and Samsung Galaxy note3. 
Though we removed the `addBondedDevices()` method, but we can still see the differences between the paired devices and the unpaired devices. So I think this is the best solution.  
N/A
=> [MRG] Removed the unreachable bluetooth devices.

skunkworks_crow/src/main/java/org/odk/share/tasks/UploadJob.java
Closes #267 
I have tested the PR using my Nexus 6P (android 8.0.1). The issue never appear again, everything went well.
This issue comes from the `finally` block, it is totally unnecessary. 
```java
try {
// show dialog and connected
Timber.d("Start Sending");
processSelectedFiles(instancesToSend);
closeConnections();
} catch (IOException e) {
Timber.e(e);
return new UploadEvent(UploadEvent.Status.ERROR, e.getMessage());
} finally {
try {
closeConnections();
} catch (IOException e) {
Timber.e(e);
}
}
```
We have already called the `closeConnections()` in the `try-catch` block and the exception comes from the `closeConnections()`, so we don't have to call `closeConnections()` again in the `finally` block, this will conduct we call this method twice and in the second time we will face the …
=> [MRG] Fixed the socket closed issue

skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java
Closes #282 
I didn't test this change, but the code makes sense. Why I didn't test that? the code still has issues that were fixed in the PR #272 . To make sure everything is safe, we can have tests after that was merged.
Clearing the devices list every time when we are starting scanning is the easiest way and can also make sure we won't forget any other cases.
N/A
=> [MRG] 🚑 quickfix: remove the previous devices list when refresh.

skunkworks_crow/src/main/java/org/odk/share/utilities/PermissionUtils.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java, skunkworks_crow/src/main/res/values/strings.xml
Closes #295 
I didn't use the permission dispatcher lib, since we already has the complete checking code, so I tried to fix this bug without a refactor. But I have tested with the permission dispatcher library as well, maybe something goes wrong with the injector, so the `OnPermissionDenied` would be called every time before I do any operations with the permission request dialog. So I just fixed the issue in the base of current code and make tests in my Nexus 6P (Android 9), everything works well.
N/A
N/A
=> [MRG] Fixed the storage permission handling progress.

skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java
Closes #306 
Tested on my Vivo Z1 Pro running on Android 9.x.x
NA
Now if the Bluetooth is enabled before sharing forms, it will not be disabled after the process is completed.
=> fix: stop bluetooth after sharing forms according to initial state

skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/BlankFormsFragment.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/FilledFormsFragment.java
Closes #242 
Now after each search query in FilledFormsFragment/BlankFormsFragment , DividerItemDecoration is not being added again and again after every update in Adapter. That's why item divider is looking as expected. Neither adding padding after every search nor going darker after every search query in both the Fragments of SendFormsActivity.
Because this should be this way. 
https://developer.android.com/reference/android/support/v7/widget/DividerItemDecoration
DividerItemDecoration added some padding to RecyclerView. Every time search query is performed previous implementation was adding DividerItemDecoration again and again that's why padding were increasing every-time a search query was performed. As you can see in previous search DividerItemDecoration was going darker and darker …
=> Fixed: RecyclerView item expand their height after each search query

skunkworks_crow/src/main/res/layout/about_list_item.xml, skunkworks_crow/src/main/res/layout/activity_bt_receive.xml, skunkworks_crow/src/main/res/layout/activity_bt_send.xml, skunkworks_crow/src/main/res/layout/activity_instance_manager_tabs.xml, skunkworks_crow/src/main/res/layout/activity_instances_list.xml, skunkworks_crow/src/main/res/layout/activity_main.xml, skunkworks_crow/src/main/res/layout/activity_review_form.xml, skunkworks_crow/src/main/res/layout/activity_send.xml, skunkworks_crow/src/main/res/layout/activity_web_view.xml, skunkworks_crow/src/main/res/layout/activity_wifi.xml, skunkworks_crow/src/main/res/layout/bottom_sheet.xml, skunkworks_crow/src/main/res/layout/dialog_password.xml, skunkworks_crow/src/main/res/layout/dialog_password_til.xml, skunkworks_crow/src/main/res/layout/fragment_forms.xml, skunkworks_crow/src/main/res/layout/fragment_instances.xml, skunkworks_crow/src/main/res/layout/fragment_stats.xml, skunkworks_crow/src/main/res/layout/list_item_bt_device.xml, skunkworks_crow/src/main/res/layout/list_item_checkbox.xml, skunkworks_crow/src/main/res/layout/list_item_single.xml, skunkworks_crow/src/main/res/layout/sort_item_layout.xml, skunkworks_crow/src/main/res/layout/toolbar.xml, skunkworks_crow/src/main/res/values/dimens.xml
Move hardcoded dimension(ex: 16dp) to dimens.xml file
Closes #326 
I ran the application on my phone(One Plus 6T Android 9.0) and it worked perfectly fine
Here, I added dimens.xml file and moved all hardcoded dimensions  to dimens.xml file
Now It will be easy to standardize dimensions of all the dimensions like height, width, text size, etc.
=> fixed:Remove hardcoded dimens from xml layout files #326

config/checkstyle.xml, config/quality.gradle, skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/BlankFormsFragment.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/FilledFormsFragment.java
…yCheck
Closes #192 
I tested it by running `./gradlew checkstyle`
I updated the `checkstyle.toolVersion` to the latest version in `quality.gradle` file. I removed the property `maxLineLength` of `LeftCurlyCheck`, as it had been deprecated in [checkstyle release 8.2.](https://checkstyle.sourceforge.io/releasenotes.html)
And I made minor changes to prevent checkstyle rule violations, in accordance with the latest version.
No, I think there are no regression risks.
=> Updated Checkstyle plugin to the latest 8.28 version

skunkworks_crow/src/main/java/org/odk/share/views/ui/instance/adapter/InstanceAdapter.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/BlankFormsFragment.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/FilledFormsFragment.java
Closes #352 
I tested it on Android 9.0.
**Android Studio Logcat on new branch:**
**Android Studio Logcat on master branch:**
I found that the `instanceAdapter` and `formAdapter` was getting attached in the `onLoadFinished` method, which is sometimes delayed. I followed the documentation at Android developers, [here](https://developer.android.com/guide/components/loaders), and found that it is better to attach the adapter in the `onCreateLoader` method, and update the cursor, later on, in `onLoadFinished` method. 
I don't think there are any regression risks, as of now.
=> Fixes Issue#352: No adapter attached; Skipping layout in BlankFormsFragment and FilledFormsFragment

skunkworks_crow/src/main/java/org/odk/share/utilities/QRCodeUtils.java, skunkworks_crow/src/test/java/org/odk/share/utilities/QRCodeUtilsTest.java
Add tests for hotspotInfo() and generateQRBitMap() of QRCodeUtils
The tests have been run to verify they work correctly
I am still looking for ways to test the Bitmap generated. Till now I am only able to verify the dimensions.
The tests may fail if unwanted changes are made to the QRCodeUtils class.
=> Unit test for QRCodeUtils.class #363

skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SetHotspotPasswordDialog.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java
Closes #370 
I tested it on Android 9.0.
I used transfered Alert Dialog inside Dialog Fragment to retain it when sreen undergoes orientation change.
No regression risks.
=> Fixes Issue#370: Used DialogFragment to retain Set Hotspot Password Dialog on screen rotation

skunkworks_crow/src/main/java/org/odk/share/views/ui/main/FormsAdapter.java, skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java
Closes #309 
- Checked whether `reviewed` and `unreviewed` count is getting perfectly or not 
- Checked whether the count is updating when on pressing the back button 
- Checked whether any new warnings are produced by adding this code
- Checked any tests are failing
- Checked by changing the orientation of the device
Removed previous approach of the query(checking every time status of form) and added the query for getting `receivedCount` and `reviewedCount` so, we can get the unReviewed count with `receivedCount-reviewedCount` and Updated the forms adapter when user presses back button from another activity in `onResume`
By updating the UI in `onResume` so, the user no need to restart the activity and get the change
=> fix: MainActivity UI is updating after updating in database
