- build.gradle
- share_app/build.gradle
> Butterknife Added

- share_app/build.gradle
- share_app/src/main/AndroidManifest.xml
- share_app/src/main/java/org/odk/share/application/Share.java
- share_app/src/main/java/org/odk/share/controller/WifiHotspot.java
> Added timber library for logging

- share_app/build.gradle
- share_app/src/main/AndroidManifest.xml
- share_app/src/main/java/org/odk/share/activities/InstancesList.java
- share_app/src/main/java/org/odk/share/adapters/InstanceAdapter.java
- share_app/src/main/java/org/odk/share/application/Share.java
- share_app/src/main/java/org/odk/share/dao/InstancesDao.java
- share_app/src/main/java/org/odk/share/dto/Instance.java
- share_app/src/main/java/org/odk/share/provider/InstanceProviderAPI.java
- share_app/src/main/java/org/odk/share/utilities/ApplicationConstants.java
- share_app/src/main/res/layout/activity_instances_list.xml
- share_app/src/main/res/layout/list_item_checkbox.xml
- share_app/src/main/res/layout/toolbar.xml
- share_app/src/main/res/values/colors.xml
- share_app/src/main/res/values/strings.xml
- share_app/src/main/res/values/styles.xml
> Screen to show Instances from odk directory

- share_app/src/main/AndroidManifest.xml
- share_app/src/main/java/org/odk/share/activities/InstancesList.java
- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/activities/SendActivity.java
- share_app/src/main/java/org/odk/share/activities/WifiActivity.java
- share_app/src/main/java/org/odk/share/controller/WifiHelper.java
- share_app/src/main/java/org/odk/share/controller/WifiHotspotHelper.java
- share_app/src/main/java/org/odk/share/dao/FormsDao.java
- share_app/src/main/java/org/odk/share/dto/Form.java
- share_app/src/main/java/org/odk/share/listeners/ProgressListener.java
- share_app/src/main/java/org/odk/share/provider/FormsProviderAPI.java
- share_app/src/main/java/org/odk/share/tasks/HotspotSendTask.java
- share_app/src/main/java/org/odk/share/tasks/WifiReceiveTask.java
- share_app/src/main/java/org/odk/share/utilities/ArrayUtils.java
- share_app/src/main/res/layout/activity_main.xml
- share_app/src/main/res/layout/activity_send.xml
- share_app/src/main/res/values/strings.xml
Closes #11 
I've created a separate activity to trigger hotspot creation and connection and after a connection is established it will start sending the forms and will finish once receiver receives the form.
To start receiving the form receiver need to tap on the wifi network then it will start receiving the form, once the tasks get finished, it will return back to MainActivity.
There are few things that I still need to take care like
> Tasks to send and receive form instances using socket connection

- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/fragments/ReceivedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/ReviewedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/SentInstancesFragment.java
- share_app/src/main/res/values/strings.xml
Closes #42 
Added display name of the form in empty form list message
> Empty form list message updated

- share_app/src/main/java/org/odk/share/activities/SendActivity.java
- share_app/src/main/java/org/odk/share/application/Share.java
- share_app/src/main/java/org/odk/share/services/ReceiverService.java
- share_app/src/main/java/org/odk/share/services/SenderService.java
- share_app/src/main/res/layout/activity_send.xml
- Cancel all pending jobs from the last session (if any)
- Fix crash due to NPE by adding a null check
- QR code now fills the entire width for better visibility
> Minor improvements

- share_app/src/main/java/org/odk/share/tasks/DownloadJob.java
Fixes #44 
Added` instance xml` filename to the `instanceFilePath` in db
> Opening forms in collect 

- share_app/src/main/AndroidManifest.xml
- share_app/src/main/java/org/odk/share/activities/SendActivity.java
- share_app/src/main/java/org/odk/share/activities/WifiActivity.java
Fixes #51 
`CHANGE_NETWORK_STATE` Permission added for Android version 5.1.1
> Support lower android versions

- share_app/src/main/java/org/odk/share/activities/WifiActivity.java
> Wifi is enabled and connected again after receiving forms 

- share_app/src/main/java/org/odk/share/activities/SendActivity.java
- share_app/src/main/java/org/odk/share/activities/WifiActivity.java
- share_app/src/main/java/org/odk/share/tasks/DownloadJob.java
- share_app/src/main/java/org/odk/share/tasks/UploadJob.java
- share_app/src/main/res/values/strings.xml
Closes #58 
I was not able to notice any dialog with such behaviour.  But by looking at the code,  it looks like that for any exception or error it returns current progress value of form transfer,  now the exception is caught and sent the ERROR STATUS in UploadEvent or DownloadEvent with error message.
> Socket connection error's handled

- share_app/src/main/java/org/odk/share/activities/WifiActivity.java
Closes #57 
Added Cancel button in the dialog shown when connecting to wifi hotspot. Also added a check before connecting to wifi using QRcode method so that first it checks if network is available or not.
> Added Cancel button in dialog

- share_app/src/main/java/org/odk/share/activities/AppListActivity.java
- share_app/src/main/java/org/odk/share/activities/FormListActivity.java
- share_app/src/main/java/org/odk/share/activities/InstanceListActivity.java
- share_app/src/main/java/org/odk/share/activities/InstancesList.java
- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/adapters/SortDialogAdapter.java
- share_app/src/main/java/org/odk/share/fragments/AppListFragment.java
- share_app/src/main/java/org/odk/share/fragments/InstanceListFragment.java
- share_app/src/main/java/org/odk/share/fragments/ReceivedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/ReviewedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/SentInstancesFragment.java
- share_app/src/main/java/org/odk/share/utilities/ApplicationConstants.java
- share_app/src/main/res/drawable/ic_access_time.xml
- share_app/src/main/res/drawable/ic_search.xml
- share_app/src/main/res/drawable/ic_sort.xml
- share_app/src/main/res/drawable/ic_sort_by_alpha.xml
- share_app/src/main/res/layout/bottom_sheet.xml
- share_app/src/main/res/layout/sort_item_layout.xml
- share_app/src/main/res/menu/list_menu.xml
- share_app/src/main/res/values/strings.xml
- share_app/src/main/res/values/styles.xml
Closes #36 
Used some of the files from collect and modified some of them as per the requirement of share app to add search and sort functionality
> Added Search & Sort in Lists

- share_app/src/main/java/org/odk/share/fragments/StatisticsFragment.java
- share_app/src/main/res/layout/fragment_instances.xml
- share_app/src/main/res/layout/fragment_stats.xml
- share_app/src/main/res/values/strings.xml
Closes #63 
Added status of a number of sent, received or reviewed instances.
> Content added in statistics screen

- share_app/src/main/java/org/odk/share/activities/SendActivity.java
- share_app/src/main/java/org/odk/share/services/SenderService.java
- share_app/src/main/res/layout/activity_send.xml
- share_app/src/main/res/values/strings.xml
Closes #51 
If a hotspot is enabled then show the QR Code else change the status.
> Showing QR Code only if hotspot is enabled

- share_app/src/main/res/values/strings.xml
Fixes #70 
`Received` string changed to `Reviewed` string
> Blank message reviewed screen modified

- share_app/src/main/AndroidManifest.xml
- share_app/src/main/assets/open_source_licenses.html
- share_app/src/main/java/org/odk/share/activities/AboutActivity.java
- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/activities/WebViewActivity.java
- share_app/src/main/java/org/odk/share/adapters/AboutAdapter.java
- share_app/src/main/java/org/odk/share/services/HotspotService.java
- share_app/src/main/res/drawable/ic_stars.xml
- share_app/src/main/res/layout/about_list_item.xml
- share_app/src/main/res/layout/activity_about.xml
- share_app/src/main/res/layout/activity_web_view.xml
- share_app/src/main/res/menu/main_menu.xml
- share_app/src/main/res/values/strings.xml
Closes #76 
Added about screen to add the usage of open source libraries/code  used in the app.
> Added screen to show libraries used

- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/res/layout/activity_main.xml
- share_app/src/main/res/values/strings.xml
Fixes #83 
Dialog added to notify user if odk collect is not installed, an option is also added which navigates user to playstore to install collect..
> Notify user if ODK Collect not installed

- share_app/src/main/java/org/odk/share/activities/MainActivity.java
Fixes #87 
Adds empty view when no blank form available
Crash resolved when moving back from stats screen
> Resolved crash when moving back from stats screen

- share_app/src/main/java/org/odk/share/activities/SendActivity.java
> Stop hotspot after transfer is completed

- share_app/src/main/java/org/odk/share/activities/SendActivity.java
- share_app/src/main/java/org/odk/share/controller/WifiHelper.java
Fixes #89 
There is an issue while triggering the wifi-hotspot when a device is already connected to some wifi-network.
> Disable wifi before triggering the Wifi-Hotspot

- share_app/src/main/java/org/odk/share/activities/InstanceManagerTabs.java
- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/adapters/FormsAdapter.java
- share_app/src/main/java/org/odk/share/adapters/basecursoradapter/BaseCursorViewHolder.java
- share_app/src/main/java/org/odk/share/adapters/basecursoradapter/CursorRecyclerViewAdapter.java
- share_app/src/main/java/org/odk/share/adapters/basecursoradapter/ItemClickListener.java
- share_app/src/main/java/org/odk/share/adapters/basecursoradapter/OnItemClickListener.java
- share_app/src/main/java/org/odk/share/dto/Form.java
- share_app/src/main/java/org/odk/share/fragments/BlankFormsFragment.java
- share_app/src/main/java/org/odk/share/fragments/StatisticsFragment.java
- share_app/src/main/java/org/odk/share/tasks/DownloadJob.java
- share_app/src/main/java/org/odk/share/tasks/UploadJob.java
- share_app/src/main/res/values/strings.xml
Tested on LG-Q6
Highlights:
- Reuse form version, name, id instead of fetching from cursor again
- Smoothens the swiping of the tabs 
- Minor code refactor
> Code cleanup and minor performance improvements

- share_app/src/main/java/org/odk/share/fragments/BlankFormsFragment.java
- share_app/src/main/java/org/odk/share/fragments/FilledFormsFragment.java
- share_app/src/main/res/layout/fragment_forms.xml
- share_app/src/main/res/values/strings.xml
* Empty view method in BlankFormsFragment.java
* Empty view method in FilledFormsFragment.java
> Show an empty view when there are no Filled Forms/Blank Forms

- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/res/layout/activity_main.xml
1- Disable the Send button at first
2- OnLoadFinished, when setEmptyViewVisibility is called, if no. of results is greater than 0, enable the Send button.
> Disable send button when there are no forms

- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/fragments/BlankFormsFragment.java
- share_app/src/main/java/org/odk/share/fragments/FilledFormsFragment.java
Closes #109 
1. Added Null Check for the cursor.
2. Called ```setEmptyViewVisibility()``` with 0 as argument in case, when cursor is null.
If there is some better solution, please let me know.
> Solves NullPointerException and Empty view problem.

- config/pmd-ruleset.xml
- share_app/src/main/java/org/odk/share/activities/AboutActivity.java
- share_app/src/main/java/org/odk/share/activities/WifiActivity.java
- share_app/src/main/java/org/odk/share/adapters/TransferInstanceAdapter.java
- share_app/src/main/java/org/odk/share/adapters/WifiResultAdapter.java
- share_app/src/main/java/org/odk/share/fragments/ReceivedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/ReviewedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/SentInstancesFragment.java
Adds unused code check and minor code refactoring
> Fixes pmd unused code

- share_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
- share_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java
- share_app/src/main/java/org/odk/collect/android/dto/Form.java
- share_app/src/main/java/org/odk/collect/android/dto/Instance.java
- share_app/src/main/java/org/odk/collect/android/provider/FormsProviderAPI.java
- share_app/src/main/java/org/odk/collect/android/provider/InstanceProviderAPI.java
- share_app/src/main/java/org/odk/share/activities/FormListActivity.java
- share_app/src/main/java/org/odk/share/activities/InstanceListActivity.java
- share_app/src/main/java/org/odk/share/activities/InstancesList.java
- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/activities/ReviewFormActivity.java
- share_app/src/main/java/org/odk/share/adapters/FormsAdapter.java
- share_app/src/main/java/org/odk/share/adapters/InstanceAdapter.java
- share_app/src/main/java/org/odk/share/dto/TransferInstance.java
- share_app/src/main/java/org/odk/share/fragments/BlankFormsFragment.java
- share_app/src/main/java/org/odk/share/fragments/FilledFormsFragment.java
- share_app/src/main/java/org/odk/share/fragments/FormListFragment.java
- share_app/src/main/java/org/odk/share/fragments/InstanceListFragment.java
- share_app/src/main/java/org/odk/share/fragments/ReceivedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/ReviewedInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/SentInstancesFragment.java
- share_app/src/main/java/org/odk/share/fragments/StatisticsFragment.java
- share_app/src/main/java/org/odk/share/tasks/DownloadJob.java
- share_app/src/main/java/org/odk/share/tasks/UploadJob.java
The intention is to separate the entire codebase of Share from Collect's Form/Instance models. This makes it easier to maintain those classes in case they are updated in Collect.
This also updates the models to the latest version
> Move Collect related classes into a new package & update models

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
I have slightly modified the templates used in @opendatakit/collect 
@yanokwa Does it look ok to you?
> Add github templates for issue and PR

- share_app/src/main/res/values/strings.xml
> updated app name

- share_app/src/main/java/org/odk/share/activities/MainActivity.java
- share_app/src/main/java/org/odk/share/fragments/BlankFormsFragment.java
- share_app/src/main/java/org/odk/share/fragments/FilledFormsFragment.java
Closes #121
1. Added list item dividers in filledformfragment and blankformfragment
If there is some better solution, please let me know.
> Added listItemDividers to filled and blank forms

- README.md
- skunkworks_crow/src/main/java/org/odk/share/activities/SendActivity.java
- skunkworks_crow/src/main/res/values/strings.xml
Closes #136 
change in the string.xml file and sendActivity file
> Change the default hotspot name #136

- build.gradle
Closes #158 
####What has been done to verify that this works as intended?
when I did the commit and ran the gradle sync in the android studio, it's not showing any error and also builds successfully thus verifying that it works as intended.
####Why is this the best possible solution? Were any other approaches considered?
Yes, this is the best possible solution.
####How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
As the dagger version is updated from 2.16 to 2.19 , users will get to use the latest versoin of the respective dagger-2 library. It's working fine also.
https://user-images.githubusercontent.com/42612183/53687851-09ad0700-3d60-11e9-82 …
> Updated dagger dependency

- CONTRIBUTING.md
- README.md
Contributing.md template is used from ODK-Collect and made some modifications according to the project and readme is also updated with the link.
> Contributing guidelines added and readme updated

- skunkworks_crow/src/main/res/layout/activity_instance_manager_tabs.xml
Closes #173 
I made the app run on a device and it's showing the expected result.
This was the best possible solution. Just one line of code added to the file.
It improves the UI/UX.
> tabs issue on rotation fixed 

- skunkworks_crow/src/main/res/layout/list_item_checkbox.xml
As I reformated the code using android studio there are so many changes have come there
Closes #202 
Tested in my phone(Samsung J8)
by adding a selectableItemBackground to the whole view so when the user clicks the button it changes the color
When the user clicks on any forms he knows he touches that particular form so giving touch feedback holds good user experience
> Added touch feedback to all forms

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- config/quality.gradle
Closes #210 
- run the gradle command and tests.
> 👷 build: updated the gradle command.

- skunkworks_crow/src/main/res/layout/toolbar.xml
> Fix #177: spacing in toolbar

- skunkworks_crow/build.gradle
- skunkworks_crow/src/main/assets/open_source_licenses.html
- skunkworks_crow/src/main/java/org/odk/share/utilities/PermissionUtils.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java
- skunkworks_crow/src/main/res/values/strings.xml
Closes #284 
Tested in my Nexus 6P (android 9.0) with success.
This fix the android 9 permission issue with bluetooth, and after this issue was resolved, the bluetooth feature can work well in android 9 devices I think. 
N/A
> [MRG] Add the location permission for android 9.

- skunkworks_crow/src/main/java/org/odk/collect/android/dao/InstancesDao.java
- skunkworks_crow/src/main/java/org/odk/collect/android/dto/Instance.java
- skunkworks_crow/src/main/java/org/odk/collect/android/provider/InstanceProviderAPI.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/instance/adapter/InstanceAdapter.java
- skunkworks_crow/src/main/res/values/strings.xml
Closes #294 
Tested in Android 9 and 7.1
There are some changes done in Collect's instances and the files are not updated for around 1 year so due to that it was crashing.
> Crash fix due to Instances table updated in Collect

- skunkworks_crow/src/main/assets/user_guide.html
- skunkworks_crow/src/main/java/org/odk/share/views/ui/about/AboutActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/about/WebViewActivity.java
- skunkworks_crow/src/main/res/values/strings.xml
Closes #289 
Verified the changes manually on Vivo Z1 Pro running on Android 9.x.x
NA
This change provides better user interaction and more information to the user about the functionality of app. There are no regression risks.
> chore: added user guide section in About section

- skunkworks_crow/src/main/java/org/odk/share/views/ui/hotspot/HpSenderActivity.java
Closes #311 
Tested this on my Vivo Z1 Pro device running on Android v9.x.x
NA
It ensures better stability of app as multiple dialogs were using a lot of android resources which was slowing down the whole android framework.
> fix: multiple dialogs for location access

- skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java
- skunkworks_crow/src/main/res/layout/dialog_password_til.xml
Closes #233 
I have run the application on my phone and it worked perfectly fine.
Here, i have used a Textwatcher.
> worked on issue  #233

- config/quality.gradle
- skunkworks_crow/src/main/java/org/odk/collect/android/dao/FormsDao.java
- skunkworks_crow/src/main/java/org/odk/share/application/Share.java
- skunkworks_crow/src/main/java/org/odk/share/services/HotspotService.java
- skunkworks_crow/src/main/java/org/odk/share/tasks/UploadJob.java
Closes #193 
I tested it by running `./gradlew pmd`.
I updates the pmd version to the latest 6.20.0 and made minor changes to fix the pmd rule violations.
No risks
> Updated PMD plugin to 6.20.0

- config/checkstyle.xml
- skunkworks_crow/src/main/java/org/odk/collect/android/dao/FormsDao.java
- skunkworks_crow/src/main/java/org/odk/share/dao/InstanceMapDao.java
- skunkworks_crow/src/main/java/org/odk/share/injection/config/AppModule.java
- skunkworks_crow/src/main/java/org/odk/share/injection/config/scopes/PerApplication.java
- skunkworks_crow/src/main/java/org/odk/share/rx/RxEventBus.java
- skunkworks_crow/src/main/java/org/odk/share/rx/schedulers/BaseSchedulerProvider.java
- skunkworks_crow/src/main/java/org/odk/share/services/HotspotService.java
- skunkworks_crow/src/main/java/org/odk/share/utilities/ArrayUtils.java
- skunkworks_crow/src/main/java/org/odk/share/utilities/PermissionUtils.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/about/AboutItem.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BluetoothListAdapter.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtReceiverActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/bluetooth/BtSenderActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/common/applist/AppListActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/common/basecursor/BaseCursorViewHolder.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/common/basecursor/CursorRecyclerViewAdapter.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/instance/InstancesList.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/instance/adapter/InstanceAdapter.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/main/FormListActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/main/MainActivity.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/BlankFormsFragment.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/send/fragment/FilledFormsFragment.java
- skunkworks_crow/src/main/java/org/odk/share/views/ui/settings/SettingsActivity.java
- skunkworks_crow/src/test/java/org/odk/share/activities/AboutActivityTest.java
- skunkworks_crow/src/test/java/org/odk/share/activities/BtReceiverActivityTest.java
- skunkworks_crow/src/test/java/org/odk/share/activities/HpReceiverActivityTest.java
- skunkworks_crow/src/test/java/org/odk/share/activities/HpSenderActivityTest.java
- skunkworks_crow/src/test/java/org/odk/share/activities/MainActivityTest.java
- skunkworks_crow/src/test/java/org/odk/share/utilities/ArrayUtilsTest.java
Closes #354 
I tested it by running `./gradlew checkstyle`
I updated the `checkstyle.xml` file and modified the `EmptyLineSeparator` module.
No regression risks, related to code maintenance.
> Closes #354: Added CheckStyle rule to check for multiple blank lines between field declarations
